@startuml PropDevelopment Smart Home Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Context diagram for PropDevelopment Smart Home

Person(resident, "Собственник", "Доступ к умному дома: домофон, шлагбаум")

System(mobile_app, "Mobile app PropDevelopment", "Мобильное приложение PropDevelopment")
System(prop_system, "PropDevelopment server", "Сервер PropDevelopment")

System_Ext(smart_intercom, "Умный домофон", "Открытие по звонку, распознование по биометрии.")
System_Ext(smart_barrier, "Умный шлагбаум", "Распознование номера автомобиля")
System_Ext(partner_service, "Сервис партнера", "Управление устройствами умного дома")

Rel(resident, mobile_app, "Send requests", "GET/POST HTTPS")

Rel(mobile_app, prop_system, "Send requests", "GET/POST HTTPS")
Rel(prop_system, partner_service, "Send requests", "HTTPS/OAuth2.0")
Rel(partner_service, smart_intercom, "Control")
Rel(partner_service, smart_barrier, "Control")

@enduml