@startuml PropDevelopment Smart Home Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container diagram for PropDevelopment Smart Home

Person(resident, "Собственник", "Доступ к умному дома: домофон, шлагбаум")

System_Boundary(prop_development, "PropDevelopment") {
    Container(mobile_app, "Мобильное приложение PropDevelopment", "iOS/Android")

    Container(smart_home_service, "Smart Home Service", "Kotlin, Spring Boot", "Сервис умного дома")

    Container(barrier_service, "Barrier Service", "Kotlin, Spring Boot", "Сервис шлагбаума")
    Container(barrier_service_db, "Barrier DB", "PostgreSQL", "БД настроек шлагбума")

    Container(intercom_service, "Intercom Service", "Kotlin, Spring Boot", "Сервис домофона")
    Container(intercom_service_db, "Intercom DB", "PostgreSQL", "БД настроек домофона")
}

System_Ext(partner_service, "Сервис партнера", "API умного дома")
System_Ext(smart_intercom, "Умный домофон", "Открытие по звонку, распознование по биометрии.")
System_Ext(smart_barrier, "Умный шлагбаум", "Распознование номера автомобиля")

Rel(resident, mobile_app, "Send requests", "GET/POST HTTPS")
Rel(mobile_app, smart_home_service, "Send requests", "HTTPS")

Rel(smart_home_service, partner_service, "Send requests", "HTTPS/OAuth2.0")
Rel(smart_home_service, intercom_service, "Send requests", "REST")
Rel(smart_home_service, barrier_service, "Send requests", "JDBC")

Rel(intercom_service, intercom_service_db, "Настройки пользователей", "JDBC")
Rel(barrier_service, barrier_service_db, "Настройки пользователей", "JDBC")

Rel(partner_service, smart_intercom, "Control")
Rel(partner_service, smart_barrier, "Control")

@enduml